### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by fkoars** [An00bRektn/gopher47#5]
![error](https://github.com/An00bRektn/gopher47/assets/94907861/ad17c28b-7b09-45ac-a17b-5bbb205b4964)
any suggestion?

**Comment by fkoars** [comment]
Yes, already on the latest dev branch
![havoc](https://github.com/An00bRektn/gopher47/assets/94907861/c8399be5-df87-4544-88e4-84662618b700)

FYI, revenant working well, but gopher47 have a issue :(
![revenant](https://github.com/An00bRektn/gopher47/assets/94907861/674940de-f511-4097-b983-0364279f369d)

**Comment by fkoars** [comment]
Replace `service.py` from Revenant repo not working.

Just added this on `service.py` , and running
```
line 9: import ssl
line 48: Thread(target=self.Socket.run_forever, kwargs={"sslopt": {"cert_reqs": ssl.CERT_NONE}}).start()
```
![run](https://github.com/An00bRektn/gopher47/assets/94907861/2a1d1dfe-d261-4c58-9845-a7c00a513b97)

But when generate, we got error  X_X
![Uploading generate.png…]()

**Comment by Cyb3rC3lt** [comment]
> Replace `service.py` from Revenant repo not working.
> 
> Just added this on `service.py` , and running
> 
> ```
> line 9: import ssl
> line 48: Thread(target=self.Socket.run_forever, kwargs={"sslopt": {"cert_reqs": ssl.CERT_NONE}}).start()
> ```

I see Revenant already has that line of code actually. Did you manage to get any 3rd party agent working? I have tried Talon, Revenent and others and although the handler will run okay the Agent will not check in!

**Comment by An00bRektn** [comment]
Apologies for the delay, I've fixed it and confirmed it works as of 1/1/24 on Havoc 0.7 (Bites the Dust).

Note that the OS Version check is a bit bugged right now because I have to rewrite more code than I was anticipating, but I've spent the first 2 hours of 2024 looking at this which is more than I was planning on doing.

**Comment by zhihuba** [comment]
> Apologies for the delay, I've fixed it and confirmed it works as of 1/1/24 on Havoc 0.7 (Bites the Dust).
> 
> Note that the OS Version check is a bit bugged right now because I have to rewrite more code than I was anticipating, but I've spent the first 2 hours of 2024 looking at this which is more than I was planning on doing.

Where to get Havoc 0.7 (Bites the Dust).
