### ISSUE TITLE
Do you have an archive available havoc 0.7

### ISSUE THREAD

**Issue by zhihuba** [An00bRektn/gopher47#6]
https://github.com/An00bRektn/gopher47/issues/5#issuecomment-1873218201

Do you have an archive available?(https://github.com/HavocFramework/Havoc/blob/main/client/src/global.cc) Although it is consistent with the 0.7 version you mentioned. But it failed.

**Comment by An00bRektn** [comment]
Hi @zhihuba, I'm afraid I can't really help you unless you have specific information about the error you're dealing with. I haven't been actively maintaining this agent because of another Havoc overhaul, but I'm like 90% confident the agent was working fine at the beginning of the year.

**Comment by zhihuba** [comment]
😂thank you for  patience. . . There is no detailed error log. I only know that the access endpoint always gets 404. There is not much difference between the packet capture through wireshark and the built-in demo. Maybe it is because post body
